import datetime
import re
from urllib.parse import urlparse, urljoin
import pandas as pd
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from tqdm import tqdm
from selenium.webdriver.support.ui import WebDriverWait
from selenium.common.exceptions import TimeoutException  # Import this for timeout handling
import time

class SightmapScraper:
    def __init__(self, websites):
        self.websites = websites
        self.webdriver_service = Service(ChromeDriverManager().install())
        self.driver = webdriver.Chrome(service=self.webdriver_service)
        self.driver.set_page_load_timeout(10)
        self.data = []

    def log_error(self, start_url, error_message):
        timestamp = datetime.datetime.now().replace(microsecond=0)
        self.data.append({
            'Website': start_url,
            'SightMap Integrated?': error_message,  # Use the error message directly
            'Time': timestamp.time(),
            'Date': timestamp.date(),
        })

    def normalize_url(self, url):
        return re.sub(r'www\.|/$', '', url.lower())

    def parse(self, soup, url, start_url):
        sightmap_found = False
        for iframe in soup.find_all('iframe', {'src': True}):
            if 'https://sightmap.com/embed/' in iframe['src']:
                sightmap_found = True
                return {
                    'sightmap_url': iframe['src'],
                    'api_usage': 'Yes' if '?enable' in iframe['src'] else 'No',
                    'closest_url_to_sightmap': url
                }
        return 'No' if not sightmap_found else None  # Return 'No' if not found

    def scrape(self):
        for start_url in tqdm(self.websites, desc="Scraping websites", unit="website"):
            if not start_url.strip():
                continue
            if not start_url.startswith(('http://', 'https://')):
                start_url = 'http://' + start_url

            try:
                self.driver.get(start_url)
                WebDriverWait(self.driver, 3).until(
                    lambda driver: driver.execute_script('return document.readyState') == 'complete')
                time.sleep(1)
                soup = BeautifulSoup(self.driver.page_source, 'html.parser')

                result = self.parse(soup, start_url, start_url)
                timestamp = datetime.datetime.now().replace(microsecond=0)
                if isinstance(result, dict):  # SightMap was found
                    self.data.append({
                        'Website': start_url,
                        'SightMap Integrated?': 'Yes',
                        'SightMap Embed': result['sightmap_url'],
                        'API Usage': result['api_usage'],
                        'Closest URL to SightMap': result['closest_url_to_sightmap'],
                        'Time': timestamp.time(),
                        'Date': timestamp.date(),
                    })
                else:  # SightMap not found or another specific error
                    self.log_error(start_url, result)
            except Exception as e:
                # For any other error, log as "404 Page / Error / Review Manually"
                self.log_error(start_url, '404 Page / Error / Review Manually')

        self.driver.quit()
        self.to_csv('SightMap Tracker Results.csv', self.data)

    def to_csv(self, filename, data):
        df = pd.DataFrame(data)
        df.to_csv(filename, index=False)

# Define your websites list here
websites = [
'https://www.essexapartmenthomes.com/apartments/the-dylan/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/the-huxley/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Cortesia/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/500-Folsom/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Axis-2300/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/1000-Kiely/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Bristol-Commons/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/City-View/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Deer-Valley/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Esplanade-San-Diego/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/500-Folsom/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Cortesia-at-Rancho-Santa-Margarita/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/101-San-Fernando/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/360-Residences/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/416-on-Broadway/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/5600-Wilshire/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/777-Hamilton/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/8th-and-Republican/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Agora-at-South-Main/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Allegro/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Allure-at-Scripps-Ranch/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Anavia/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Annaliese/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Aqua-at-Marina-Del-Rey/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Arbors-at-Parc-Rose/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Ascent/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Ashton-Sherman-Village/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Audrey-at-Belltown/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/avant/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Avenue-64/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Avery/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Aviara/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Avondale-at-Warner-Center/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Axis-2300/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Barkley/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Bel-Air/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Belcarra/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Bella-Villagio/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/BellCentre/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Bellerive/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Belmont-Station/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Belmont-Terrace/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Bernardo-Crest/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Bonita-Cedars/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Bothell-Ridge/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Boulevard/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Briarwood-at-Central-Park/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Bridgeport/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Bridgeport-Coast/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Bridle-Trails/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Brighton-Ridge/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Brio/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Brookside-Oaks/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Skye-at-Bunker-Hill/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Cairns/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Camarillo-Oaks/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Cambridge-Park/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Camino-Ruiz-Square/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Canyon-Oaks-at-Windemere/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Canyon-Pointe/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Capri-at-Sunny-Hills/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Carlyle/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Carmel-Creek/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Carmel-Landing/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Carmel-Summit/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Castle-Creek/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Catalina-Gardens/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Cedar-Terrace/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/CentrePointe/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Century-Towers/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Chestnut-Street/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/City-Centre/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Collins-on-Pine/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Commons/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Connolly-Station/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Corbella-at-Juanita-Bay/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Country-Villas/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Courtyard-Off-Main/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Courtyards-at-65th/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Crow-Canyon/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Devonshire/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Domaine/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Elevation/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Ellington-at-Bellevue/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Elliot-at-Mukilteo/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Emerald-Pointe/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Emerald-Ridge/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Emerson-Valley-Village/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Emme/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Enso/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Epic/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Esplanade/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Evergreen-Heights/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Expo/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Fairhaven/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Fairway-at-Big-Canyon/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Fairways-at-Westridge/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Fairwood-Pond/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Foothill-Commons/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Foothill-Gardens/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Forestview/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Form-15/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Fosters-Landing/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Fountain-Park-at-Playa-Vista/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Fountains-at-River-Oaks/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Fourth-and-U/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Fox-Plaza/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Gas-Company-Lofts/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Grand/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Haver-Hill/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Highlands-at-Wynhaven/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Highridge/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Hillsborough-Park/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Huntington/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Huntington-Breakers/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Inglenook-Court/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Blake-LA/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Lafayette-Highlands/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Lakeshore-Landing/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Landing-at-Jack-London-Square/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Laurels-at-Mill-Creek/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Lawrence-Station/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Le-Parc/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Lofts-at-Pinehurst/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Magnolia-Square/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Marbrisa/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Marina-Cove/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Mariners-Place/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Marquis/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Meadowood/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Meridian-at-Midtown/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Mesa-Village/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Mio/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Mira-Monte/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Mirabella/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Mission-Hills/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Mission-Peaks/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Mission-Peaks-II/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Montanosa/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Montclaire/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Montebello/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Montejo/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Monterey-Villas/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Muse/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Museum-Park/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Mylo-Santa-Clara/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/One-South-Market/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Pacific-Electric-Lofts/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Palisades/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Palma-Sorrento-at-Palm-Valley/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Santa-Palmia-at-Palm-Valley/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Villa-Veneto-at-Palm-Valley/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Palms-at-Laguna-Niguel/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Paragon/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Park-20/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Park-Catalina/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Park-Highland/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Park-Hill-at-Issaquah/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Park-Viridian/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Park-West/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Parkside-Court/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Parkwood-at-Mill-Creek/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Patent-523/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Pathways-at-Bixby-Village/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Piedmont/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Pinehurst/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Pinnacle-at-Fullerton/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Pinnacle-at-MacArthur-Place/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Pinnacle-at-Otay-Ranch/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Pinnacle-at-Talega/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Pinnacle-on-Lake-Washington/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Pinnacle-Sonata/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Pointe-at-Cupertino/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Promenade-At-Marina-City-Club/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Radius/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Redmond-Hill/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Reed-Square/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Regency-at-Encino/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Regency-at-Mountain-View/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Regency-Palm-Court/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Reveal/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Riley-Square/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Sage-at-Cupertino/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Salmon-Run-at-Perry-Creek/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Sammamish-View/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/San-Marcos/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Santee-Court/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Shadow-Point/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Shadowbrook/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Essex-Skyline-at-MacArthur-Place/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Slater-116/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Solstice/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Stevenson-Place/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Stonehedge-Village/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Stuart-at-Sierra-Madre-Villa/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Summerhill-Park/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Summit-Park-Village/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Taylor-28/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Tierra-Vista/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Tiffany-Court/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Township/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Trabuco-Villas/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Trails-of-Redmond/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Valley-Park/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Verandas/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Vesta/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Via/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Villa-Angelina/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Villa-Granada/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Villa-Siena/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Village-at-Toluca-Lake/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Village-Green/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Vista-Belvedere/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Vistas-of-West-Hills/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Vox/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Walnut-Heights/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Wandering-Creek/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Waterford-Place/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Wharfside-Pointe/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Willow-Lake/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Wilshire-La-Brea/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Wilshire-Promenade/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Windsor-Court/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Woodland-Commons/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Woods/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Woodside-Village/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Windsor-Ridge/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Dylan/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Huxley/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Havens/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Apex/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Alpine-Village/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Alessio/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Hillsdale-Garden/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Fountain-Court/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Bernard/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Hillcrest-Park/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Galloway/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Foothill/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Mill-Creek-at-Windemere/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Miracle-Mile/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Hope-Ranch/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/MB360/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Station-Park-Green/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Renaissance-at-uptown-Orange/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Henley-All-Buildings/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/CBC-and-The-Sweeps/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Bennett-Lofts/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Hallie/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Pure-Redmond/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Velo-and-Ray/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Patina-At-Midtown/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Mission-Hills-Draft/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Henley/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Henley-on-Columbus-Parking/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Wallace-On-Sunset/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/500-Folsom/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Huntington-Breakers/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Anavia/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Huntington-Breakers/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Montejo/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Park-Viridian/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Pinnacle-at-MacArthur-Place/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Renaissance-at-Uptown-Orange/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Havens/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Huntington/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Valley-Park/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Villa-Siena/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Allure-at-Scripps-Ranch/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Bernardo-Crest/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Cambridge-Park/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Carmel-Landing/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Carmel-Summit/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Esplanade/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Mesa-Village/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Mira-Monte/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Montanosa/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Martha-Lake-Apartments/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Esplanade-San-Diego/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Villa-Angelina/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Barkley/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Emerald-Pointe/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Village-Green/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Hillsborough-Park/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Walnut-Heights/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Haver-Hill/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Capri-at-Sunny-Hills/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Wilshire-Promenade/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Pinnacle-at-Fullerton/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Monterra-in-Mill-Creek/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Passage-Buena-Vista/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Passage-Buena-Vista/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Rexford/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Canvas-Apartments/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Silver-Apartments/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Silver-Apartments/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Vela-on-Ox/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/1000-Kiely/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/101-San-Fernando/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/360-Residences/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/416-on-Broadway/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/5600-Wilshire/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/777-Hamilton/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/8th-and-Republican/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Agora-At-South-Main/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Alessio/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Allegro/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Alpine-Village/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Anavia/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Annaliese/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Apex/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Aqua-At-Marina-Del-Rey/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Arbors-at-Parc-Rose/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Ascent/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Ashton-Sherman-Village/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Audrey-At-Belltown/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Avant-I-and-II/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Avenue-64/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Avery/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Aviara/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Avondale-at-Warner-Center/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Axis-2300/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Bel-Air/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Belcarra/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Bella-Villagio/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/BellCentre/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Bellerive/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Belmont-Station/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Belmont-Terrace/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Bennett-Lofts/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Bernard/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Bonita-Cedars/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Bothell-Ridge/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Boulevard/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Briarwood-at-Central-Park/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Bridgeport/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Bridgeport-Coast/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Bridle-Trails/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Brighton-Ridge/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Brio/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Bristol-Commons/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Brookside-Oaks/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Cairns/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Camarillo-Oaks/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Camino-Ruiz-Square/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Canvas/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Canyon-Oaks-at-Windemere/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Canyon-Pointe/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Carlyle/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Carmel-Creek/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Castle-Creek/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Catalina-Gardens/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Cedar-Terrace/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/CentrePointe/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Century-Towers/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Chestnut-Street/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/City-Centre/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/City-View/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Collins-on-Pine/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Commons/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Connolly-Station/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Corbella-at-Juanita-Bay/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Cortesia-at-Rancho-Santa-Margarita/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Country-Villas/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Courtyard-Off-Main/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Courtyards-at-65th/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Crow-Canyon/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Deer-Valley/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Devonshire/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Domaine/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Elevation/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Ellington-at-Bellevue/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Elliot-at-Mukilteo/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Emerald-Ridge/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Emerson-Valley-Village/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Emme/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Enso/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Epic/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Essex-Skyline-at-MacArthur-Place/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Evergreen-Heights/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Expo/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Fairhaven/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Fairway-at-Big-Canyon/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Fairways-at-Westridge/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Fairwood-Pond/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Foothill/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Foothill-Commons/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Forestview/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Form-15/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Fosters-Landing/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Fountain-Court/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Fountains-at-River-Oaks/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Fountain-Park-at-Playa-Vista/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Fourth-and-U/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Fox-Plaza/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Galloway/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Gas-Company-Lofts/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Highridge/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Hillcrest-Park/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Hillsdale-Garden/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Hope-Ranch/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Huntington-Breakers/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Inglenook-Court/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Lafayette-Highlands/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Lakeshore-Landing/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Laurels-at-Mill-Creek/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Le-Parc/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Lawrence-Station/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Magnolia-Square/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Marbrisa/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Marina-Cove/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Mariners-Place/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Marquis/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/MB-360/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Meadowood/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Meridian-at-Midtown/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Mill-Creek-at-Windemere/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Mio/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Mirabella/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Miracle-Mile/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Mission-Hills/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Mission-Peaks/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Mission-Peaks-II/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Montebello/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Montejo/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Monterey-Villas/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Muse/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Mylo-Santa-Clara/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Pacific-Electric-Lofts/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Palisades/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Palma-Sorrento-at-Palm-Valley/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Paragon/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Park-20/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Park-Catalina/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Park-Highland/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Park-Hill-at-Issaquah/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Park-Viridian/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Park-West/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Parkside-Court/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Parkwood-at-Mill-Creek/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Patent-523/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Patina-at-Midtown/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Pathways-at-Bixby-Village/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Piedmont/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Pinehurst/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Pinnacle-at-MacArthur-Place/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Pinnacle-at-Otay-Ranch/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Pinnacle-at-Talega/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Pinnacle-on-Lake-Washington/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Pinnacle-Sonata/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Pure-Redmond/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Radius/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Redmond-Hill/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Reed-Square/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Regency-at-Encino/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Regency-at-Mountain-View/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Regency-Palm-Court/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Renaissance-at-Uptown-Orange/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Reveal/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Riley-Square/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Sage-at-Cupertino/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Salmon-Run-at-Perry-Creek/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Sammamish-View/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/San-Marcos/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Santa-Palmia-at-Palm-Valley/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Santee-Court/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Shadow-Point/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Shadowbrook/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Slater-116/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Solstice/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Station-Park-Green/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Stevenson-Place/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Stonehedge-Village/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Summerhill-Park/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Summit-Park-Village/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Taylor-28/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Blake-LA/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Dylan/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Grand/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Hallie/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Havens/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Highlands-at-Wynhaven/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Henley/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Huntington/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Huxley/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Landing-at-Jack-London-Square/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Lofts-at-Pinehurst/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Montclaire/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Palms-at-Laguna-Niguel/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Pointe-at-Cupertino/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Promenade-at-Marina-City-Club/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Rexford/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Stuart-at-Sierra-Madre-Villa/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Trails-of-Redmond/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Village-at-Toluca-Lake/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Vistas-of-West-Hills/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/The-Woods/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Tierra-Vista/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Tiffany-Court/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Township/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Trabuco-Villas/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Valley-Park/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Velo-and-Ray/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Vesta/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Verandas/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Via/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Villa-Granada/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Villa-Sienna/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Villa-Veneto-at-Palm-Valley/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Vista-Belvedere/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Vox/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Wallace-on-Sunset/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Wandering-Creek/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Waterford-Place/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Wharfside-Pointe/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Willow-Lake/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Wilshire-La-Brea/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Windsor-Court/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Windsor-Ridge/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Woodland-Commons/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Woodside-Village/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Skye-at-Bunker-Hill/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/CBC-and-The-Sweeps/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Vela-on-Ox/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/500-Folsom/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Livia/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Martha-Lake-Apartments/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Monterra-in-Mill-Creek/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Livia/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/1000-Kiely/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Hacienda-de-Camarillo/floor-plans-and-pricing#interactiveSightMap',
'https://www.essexapartmenthomes.com/apartments/Hacienda-de-Camarillo/floor-plans-and-pricing#interactiveSightMap',
]

scraper = SightmapScraper(websites)
scraper.scrape()
